PartnerManagementService:
    Db:
        LogsConnString:
            settings-key: PartnerManagementService-LogsConnString
            types:
              - AzureTableStorage
        MsSqlConnectionString:
            settings-key: PartnerManagementService-MsSqlConnectionString
    Authentication:
        GeneratedUsernameLength:
            settings-key: PartnerManagementService-GeneratedUsernameLength
        GeneratedPasswordLength:
            settings-key: PartnerManagementService-GeneratedPasswordLength
        SessionsServiceTokenTimeToLiveInSeconds:
            settings-key: PartnerManagementService-SessionsServiceTokenTimeToLiveInSeconds
    RabbitMq:
        RabbitMqConnectionString:
            settings-key: UserManagementRabbitMQ
            types:
              - RabbitMq
    Geocoding:
        ApiKey:
            settings-key: PartnerManagementService-GeocodingApiKey
        Url:
            settings-key: PartnerManagementService-GeocodingUrl
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
SessionsServiceClient:
  ServiceUrl:
    settings-key: AdminSessionsServiceUrl

CredentialsServiceClient:
    ServiceUrl :
        settings-key: PartnerCredentialsServiceUrl

PartnersIntegrationServiceClient:
    ServiceUrl :
        settings-key: PartnersIntegrationServiceUrl
        
CustomerProfileServiceClient:
    ServiceUrl:
        settings-key: CustomerProfileServiceUrl

PaymentManagementServiceClient:
    ServiceUrl:
        settings-key: PaymentManagementServiceUrl

ReferralServiceClient:
    ServiceUrl:
        settings-key: ReferralServiceUrl

KycServiceClient:
    ServiceUrl:
        settings-key: KycServiceUrl

MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl



